name: Run Terraform
on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: 'Virtual Machine SKU'
        required: true
        default: 'n1-standard-8'
      guest_accelerator:
        required: true
        default: 'nvidia-tesla-p100'
      guest_accelerator_count:
        required: true
        default: '1'
      disk_size:
        description: 'Disk size (GB)'
        required: true
        default: '64'
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.TERRAFORM_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - uses: actions/checkout@v3
    - name: Terraform fmt
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform fmt
      continue-on-error: false
      shell: bash

    - name: Terraform Init
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform init --upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate -no-color
      continue-on-error: false
      shell: bash
      
    - name: Terraform Plan
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform plan -no-color \
          -var="machine_type=$MACHINE_TYPE" \
          -var="guest_accelerator=$GUEST_ACCELERATOR" \
          -var="guest_accelerator_count=$GUEST_ACCELERATOR_COUNT"
          -var="disk_size=$DISK_SIZE"
      continue-on-error: false
      shell: bash
      env:
        MACHINE_TYPE: ${{github.event.inputs.machine_type}}
        GUEST_ACCELERATOR: ${{github.event.inputs.guest_accelerator}}
        GUEST_ACCELERATOR_COUNT: ${{github.event.inputs.guest_accelerator_count}}
        DISK_SIZE: ${{github.event.inputs.disk_size}}

