name: Terraform Comand
on:
  workflow_dispatch:
    inputs:
      terraform_command:
        description: 'Command to run'
        required: true
        default: 'destroy'
permissions:
  pull-requests: write

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3

    - name: Terraform Init
      id: init
      run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform hashicorp/terraform init -upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      id: validate
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate -no-color
      continue-on-error: false
      shell: bash
    
    - name: Terraform Destroy
      run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform ${{ github.event.inputs.terraform_command }} \
          -var="organization=${{ secrets.ORGANIZATION }}" \
          -var="organization_id=${{ secrets.ORGANIZATION_ID }}" \
          -var="billing_account=${{ secrets.BILLING_ACCOUNT }}" -auto-approve -input=false
      shell: bash
      continue-on-error: false
