name: Terraform PR
on: pull_request
permissions:
  pull-requests: write

jobs:
  terraform-pr:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Terraform fmt
      id: fmt
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform fmt
      continue-on-error: false
      shell: bash

    - name: Terraform Init
      id: init
      run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform hashicorp/terraform init -upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      id: validate
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate -no-color
      continue-on-error: false
      shell: bash
    
    - name: Terraform Plan
      id: plan
      run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform plan \
          -var="organization='${{ secrets.ORGANIZATION }}'" \
          -var="organization_id='${{ secrets.ORGANIZATION_ID }}'" \
          -var="billing_account='${{ secrets.BILLING_ACCOUNT }}'" \
          -no-color -lock=false -out terraform.plan
      continue-on-error: true

    # generate plain output
    - run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform show -no-color terraform.plan > terraform.text

    # generate json output
    - run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform show -json terraform.plan > terraform.json

    - uses: ahmadnassri/action-terraform-report@v3
      with:
        # tell the action the plan outputs
        terraform-text: ${{ github.workspace }}/terraform.text
        terraform-json: ${{ github.workspace }}/terraform.json
        remove-stale-reports: true
        
    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        docker run --platform linux/amd64 \
          -e GOOGLE_CREDENTIALS='${{ secrets.TERRAFORM_KEY }}' \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform apply -auto-approve -input=false
